### ISSUE TITLE
Screenshots not captured for "takeWebElementScreenshot" and "takeWebElementsScreenshot"

### ISSUE THREAD

**Issue by zeeshanyshaikh** [katalon-studio/katalon-studio-ashot-plugin#2]
Am not able to capture screenshots for "**takeWebElementScreenshot**" and "**takeWebElementsScreenshot**" using below code.

```
CustomKeywords.'kms.turing.katalon.plugins.visualtesting.ScreenCapture.takeScalingScreenshot'('cutting_screen.png', 2,  FailureHandling.OPTIONAL)
CustomKeywords.'kms.turing.katalon.plugins.visualtesting.ScreenCapture.takeWebElementScreenshot'(findTestObject('Page_antenna/img_logo'), "logo.png", 10, FailureHandling.OPTIONAL)
```

got below as warning message in Katalon Studio.

> org.openqa.selenium.JavascriptException: TypeError: $ is not a function

even though the test case shown as passed, screenshot is not saved in "Screenshot" folder.
> kms.turing.katalon.plugins.visualtesting.ScreenCapture.takeWebElementScreenshot is PASSED

I have created plugin for this project, using 
* build.gradle of "https://github.com/katalon-studio/katalon-studio-ashot-keywords-plugin/blob/master/build.gradle
* And katalon-plugin.json as 
```
{
    "keywords": ["kms.turing.katalon.plugins.visualtesting.ScreenCapture", "kms.turing.katalon.plugins.visualtesting.ImageComparision"]
}
```

**Comment by Eyalzi** [comment]
Got the same error..

**Comment by zeeshanyshaikh** [comment]
Any update on this?

**Comment by devalex88** [comment]
Hi. Since Ashot depends on jQuery, the web app must include the library.
